manifest:
  remotes:
    - name: lowprokb
      url-base: https://github.com/LOWPROKB
  projects:
    - name: zmk
      remote: lowprokb
      revision: Board-Corne-ish-Zen-dedicated-work-queue
      import: app/west.yml
  self:
    path: config
